{% set version = '0.9.5.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jmvcore
  version: {{ version|replace("-", "_") }}

source:
  fn: jmvcore_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/jmvcore_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jmvcore/jmvcore_{{ version }}.tar.gz
  sha256: d987399564b6d1c155379833efb302d65d2b08370d81cffb9c52775fb1f0ff5a

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-r6 >=1.0.1
    - r-rlang >=0.3.0.1
    - r-rjson
    - r-base64enc
    - r-stringi
  run:
    - r-base
    - r-r6 >=1.0.1
    - r-rlang >=0.3.0.1
    - r-rjson
    - r-base64enc
    - r-stringi

test:
  commands:
    - $R -e "library('jmvcore')"           # [not win]
    - "\"%R%\" -e \"library('jmvcore')\""  # [win]

about:
  home: https://www.jamovi.org
  license: GPL (>= 2)
  summary: A framework for creating rich interactive analyses for the jamovi platform (see <https://www.jamovi.org>
    for more information).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
