{% set version = "2.3.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jmvcore
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jmvcore_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jmvcore/jmvcore_{{ version }}.tar.gz
  sha256: 0a4f1255dfc5f8db72a6ce974397c3b41b624bb45f7ef5b53c5f6cdb011a6cf9

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6 >=1.0.1
    - r-base64enc
    - r-rjson
    - r-rlang >=0.3.0.1
    - r-stringi
    - r-jsonlite
  run:
    - r-base
    - r-r6 >=1.0.1
    - r-base64enc
    - r-rjson
    - r-rlang >=0.3.0.1
    - r-stringi
    - r-jsonlite

test:
  commands:
    - $R -e "library('jmvcore')"           # [not win]
    - "\"%R%\" -e \"library('jmvcore')\""  # [win]

about:
  home: https://www.jamovi.org
  license: GPL-2.0-or-later
  summary: A framework for creating rich interactive analyses for the jamovi platform (see <https://www.jamovi.org> for more information).
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: jmvcore
# Type: Package
# Title: Dependencies for the 'jamovi' Framework
# Version: 1.0.0
# Date: 2019-05-28
# Author: Jonathon Love
# Maintainer: Jonathon Love <jon@thon.cc>
# Description: A framework for creating rich interactive analyses for the jamovi platform (see <https://www.jamovi.org> for more information).
# URL: https://www.jamovi.org
# BugReports: https://github.com/jamovi/jmvcore/issues
# License: GPL (>= 2)
# ByteCompile: yes
# Depends: R (>= 3.2)
# Imports: R6 (>= 1.0.1), rlang (>= 0.3.0.1), rjson, base64enc, stringi
# Suggests: testthat (>= 1.0.2), RProtoBuf, knitr, ggplot2, RColorBrewer
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-05-28 00:33:00 UTC; jonathon
# Repository: CRAN
# Date/Publication: 2019-05-28 04:50:08 UTC
