# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "m7s4GVhUjeupBYesESRvc++WMa5XydJjlI2NJKh8QVH5SJFAj9ApnqfhT0UTvhTdzUo3/Rh77tX1Ru45D24iq/HnOyT3vJWSmorgAFcK8yTzL8ic29yIl3qH+KPCqCqe/DinbrdO+2Pgh5+N4m9jS9xwQnvBg/zKCKFyhCQGgaNY988jQUXktcCWQ+Q1b96Z2oYTMFyHVWRK6CR+D+dTSI5s4ztTQspSIBSS5wrICuIlurhpzOZpVg8d/YI6CrryFaS+t8QVMMJGo9PHT4f+7H67FxNa53/FeE99r17Arb61sbl4IiQQUmLTCX55xOSJl4mWCXau1M+roeyY9aF8UjzEdxFYuCH1Nc+Fveg7nxkebIpW3Cnaz8PD2FedyCMohgkr7IUcXgE4sF/INedMu8J2EljLNTXuFkZWYG+gLP6vIaM71CNlKK4prNteCn9uLTE1/IHGLcoTgxdpvd287bV4iFIaQCUbO/LHtDYkMB0KWiZVJdagXzqbZ1/9u8XfTPI6evdBOIMyWj3h1y2v3tL6b8viudULUidwzGQnr9WD59MgDLDNAkVkCbCzgRNsYMp+Tbqfv4zd+vUUuY2a2CVZIwoJx4djJSfaQ8HuWFPfvcRzkXlGGtDDrkkU4SzY3w/DOoqfMZlNMDNhD1oIg7Qw6EMhj9RURZsnFqHgZWU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
