appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: m7s4GVhUjeupBYesESRvc++WMa5XydJjlI2NJKh8QVH5SJFAj9ApnqfhT0UTvhTdzUo3/Rh77tX1Ru45D24iq/HnOyT3vJWSmorgAFcK8yTzL8ic29yIl3qH+KPCqCqe/DinbrdO+2Pgh5+N4m9jS9xwQnvBg/zKCKFyhCQGgaNY988jQUXktcCWQ+Q1b96Z2oYTMFyHVWRK6CR+D+dTSI5s4ztTQspSIBSS5wrICuIlurhpzOZpVg8d/YI6CrryFaS+t8QVMMJGo9PHT4f+7H67FxNa53/FeE99r17Arb61sbl4IiQQUmLTCX55xOSJl4mWCXau1M+roeyY9aF8UjzEdxFYuCH1Nc+Fveg7nxkebIpW3Cnaz8PD2FedyCMohgkr7IUcXgE4sF/INedMu8J2EljLNTXuFkZWYG+gLP6vIaM71CNlKK4prNteCn9uLTE1/IHGLcoTgxdpvd287bV4iFIaQCUbO/LHtDYkMB0KWiZVJdagXzqbZ1/9u8XfTPI6evdBOIMyWj3h1y2v3tL6b8viudULUidwzGQnr9WD59MgDLDNAkVkCbCzgRNsYMp+Tbqfv4zd+vUUuY2a2CVZIwoJx4djJSfaQ8HuWFPfvcRzkXlGGtDDrkkU4SzY3w/DOoqfMZlNMDNhD1oIg7Qw6EMhj9RURZsnFqHgZWU=}
