travis:
  secure:
    BINSTAR_TOKEN: gvIsQ5061SQ2yJb9Di5LYYOAykf1hi0mqlpdreSWTW4fo+ae8Gv7LtMUnuZmmQaNh048QOUW/XXO3YzvOQ3ufdvmZDqyKC9i7ncKSnC3Ga8wXm8rZ9xiWGnoIkfS5RnLcd3fKH7aTtBRqW7TEjOz7e0fcrN5Pwh/R/EagRc3LqairkQONUMYHEa2yW3wS1e3geKDNxOysW6FJxHdM9NUla8HRGlUvB9ePZ5zfhBD99s1K0tj28KfaSovNyeV9fWsLjWy1rmhG3eP+oEOB29COc1W5Crl6XE2nlc76ufAEK7oCMhnOs/5MIBf96XbJ+tlaW7aFGnIjfhd2rT2msOKTagno/ZvPt5rycUZpFmRC1fR2JIW7JgGK2cfZddBIOkrO6eR/f4qWp6DlHtQm7DxdVY31TMx97pAxdA5Et9YPG55JgKGmb1MQFry2KOQ5zIMEnFQAzdttWmiubJfNg+YHHjEWUM5303RHgAK5it8nevqI/a38GCJVKr4A+ckeNsSMuudPaxwAycGoEdP92CoWMH0DOlNC9oOO1710FACtKkp8VfM9bVdQG8xxsApDMHFSIepm3biGQyNIFoIZreiPzTodg634myKvuERHpcTfHKxOx7yL9Nrv4n8W6k4HkNfhaJi+ibd3uYO/ROmoJyheF3m+w9GzpW8azA6xlPLpRQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
