travis:
  secure:
    BINSTAR_TOKEN: BBqEYI8CXnxfgSzXMuYtIqgYU2G1XNpXiBISSign1GxRqNwvyu40oKOmB/FLzTq5kpkp2b7mb3oNYNJT0HdvaeIFd4pYr0UMwmMxFPU+3lXnY+/YeOVanp5dB1lPRyCqbmioAKPTOmgGswaW6sfs1P3wuwoR1GGBp9ciHVf15kMZ0U/ypD3pgRQaIissr7qydpTz+WW7YpoCqAnWKSN1coMKoJmrvs6wiBm2q7wBmPvpeluqNatw+AU7hX3W61GiABg8oNplG0gnr5z69qRhLjIQPVQ9tMo3/UO/xlvNacoil0gh5qZr6aVzFLmhDua+78UON6wD+Qiftgky2zMWB1MKY5tnniNU9aaGFAaZwHUEFGAD3xywvM+2FYBs9L28g7SJV2bkuXJWadzsJauI1yUCaN5aF3WIMORyiUhZrT9xfFIyXzIt4WSevjcEmFj5sTkT/bB/C//0P02Mgi7Y9cGtmvYa6BExR6MrZKoMJdhVZUxoPVDHMHJ4fCQ9Gg0g3einoeBBcft032VW5XJD9km1dRM29wAPTuc5yHdl73ESAiTRnV4MI+AfsNGCz8/FMDff7JVFLNaZ56VZ30A15h7pLi5aRcAdt1swZJBNZcxg4voBaQYDLb20gIjOdHn47ODNO+o0WLylSa79igQmFDDlur3FZLTqetyvtBAdvfE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
